### ISSUE TITLE
Is it correct that AIK activation is not covered by the spec?

### ISSUE THREAD

**Issue by arianvp** [brandonweeks/draft-bweeks-acme-device-attest#3]
I've been trying to follow the webauthn spec's `tpm` attestation. But at what point of the flow do we prove that the `AK` and the `EK` are on the same device here?    It only seems to check that the `AK` signed the challenge and that the Attestation CA signed the `AK` but it does not perform the activation handshake that proves that the EK and AK are on the same cryptographic device before signing the AK. They just say "It's the responsibility of the Attestation CA to check that the EK and AK are there") Is that something that is planned to be added to this spec? Or did I read over it? as it seems like an important part of attestation to actually check that the device is genuine.

**Comment by arianvp** [comment]
Looking at the demo it seems that the whole "Attestation CA" part is  indeed missing; as the AK is signed without any verification with the Root CA unconditionally without first calling https://pkg.go.dev/github.com/google/go-attestation/attest#AK.ActivateCredential to make sure the device is "legit" .   https://github.com/brandonweeks/acme-device-attest-demo/blob/main/client/client.go#L78

**Comment by arianvp** [comment]
ah I guess this would be part of the `hardware-module` validation method; which isn't specified in the draft yet?

**Comment by hslatman** [comment]
@arianvp from a discussion with @brandonweeks I concluded that the "Attestation CA" part is intentionally omitted from the RFC, because it would be very dependent on the (TPM/TEE) platform and thus hard to sufficiently specify in a standard. It is expected that a device in need of a DA proof for ACME DA interacts with another system, the "Attestation CA", also sometimes called "Privacy CA" or "Anonymization CA"; and perhaps other names, before interacting with an ACME server. How and when a device does this, is essentially up to the parties involved in manufacturing and using the device. 

For iOS, the servers are provided by Apple and attestation involves checking against the manufacturing records they have for the device before a device is issued a certificate. In https://github.com/smallstep/certificates/ we also support ACME DA with Yubikeys, which can create an attestation certificate themselves using the embedded intermediate CA every Yubikey has. Other platforms could implement something similar to the Yubikey or Apple, depending on security requirements, and probably already do so. I'm not aware of a fully specified, standardized protocol to perform this step, but the example at https://github.com/google/go-attestation#example-device-identity and the description at https://tpm2-software.github.io/tpm2-tss/getting-started/2019/12/18/Remote-Attestation.html offer some guidance on what such a protocol would look like. A notable open source project that includes device attestation is https://keylime.dev/, but it goes further than just device identity attestation: it also does measured boot verification and runtime integrity attestation.

I've described my own adaptation of the attestation flow (and ACME DA) in a blog at https://smallstep.com/blog/managed-device-attestation/#trusted-platform-module-tpm-attestation and have a POC for the attestation CA that we maybe are going to expand on, but hasn't been planned nor fully thought-out yet.

**Comment by arianvp** [comment]
This is very helpful. Thanks for the explanation.

I'm still curious what the `hardware-module` part of this spec is gonna look like though.

**Comment by hslatman** [comment]
My understanding of that section is that an ACME client can send a CSR with a [HardwareModuleName](https://www.rfc-editor.org/rfc/rfc4108#section-5) SAN. That CSR must be signed by a private key created in the TPM. The ACME server then has to verify the properties of the attestation object accordingly.

In the example client a `PermanentIdentifier` is used, but that can also be a `HardwareModuleName` (the value of which first has to be read from the TPM). In https://github.com/brandonweeks/acme-device-attest-demo/blob/main/client/client.go#L281-L295 a new private key is created inside the TPM that is attested by the AK. The resulting private key has a reference to its certification parameters that are included in the attestation statement that is sent to the ACME server: https://github.com/brandonweeks/acme-device-attest-demo/blob/160b88dfb210a0f074232514eaf31d57975be715/client/client.go#L118-L131. That part is in the `CreateAttestation` property, which is a `TPMB_Attest` structure in TPM parlance (I believe; the Go pkg doc states it's `TPMS_Attest`). The CA can read this property and verify the key resides in the TPM.

I'm not entirely sure yet if this is how it's supposed to work and if we're going to implement it like this in `step-ca`. I think the main ideas are in the right direction, though.

**Comment by arianvp** [comment]
Sounds clear! I'll close this issue

**Comment by brandonweeks** [comment]
https://www.ietf.org/mailman/listinfo/acme

If you have any other feedback, feel free to start a thread on the ACME WG mailing list. Any input from people thinking about how they'd implement the spec is greatly appreciated.

I've also made a note to myself to add a real Attestation CA to the demo and make it a touch less fake.
